# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challeges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField(blank=True, null=True)),
                ('hacker_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_submission', models.CharField(blank=True, max_length=250)),
                ('total_accept_submission', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='View_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.CharField(blank=True, max_length=250)),
                ('total_uniqueviews', models.CharField(blank=True, max_length=250)),
                ('challeges_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_statement.Challeges')),
            ],
        ),
        migrations.AddField(
            model_name='submission_stats',
            name='challeges_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_statement.View_Stats'),
        ),
        migrations.AddField(
            model_name='colleges',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_statement.Contests'),
        ),
        migrations.AddField(
            model_name='challeges',
            name='challeges_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_statement.Colleges'),
        ),
    ]
