# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-02 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_statement', '0002_auto_20181202_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challeges_id', models.IntegerField(blank=True, null=True)),
                ('college_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='challeges',
            name='challeges_id',
        ),
        migrations.RemoveField(
            model_name='submission_stats',
            name='challeges_id',
        ),
        migrations.RemoveField(
            model_name='view_stats',
            name='challeges_id',
        ),
        migrations.AddField(
            model_name='submission_stats',
            name='challenges_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='view_stats',
            name='challenges_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colleges',
            name='contest_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Challeges',
        ),
    ]
