# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-02 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem_statement', '0003_auto_20181202_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='challeges_id',
            new_name='challenges_id',
        ),
    ]
